service: naics-api

custom:
  defaultRegion: us-east-1
  defaultStage: test
  dynamoTable:
    tblName: naics
    tblPartKey: NAICSYear
    tblSortKey: CodeLenAndCode

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  # profile: ${self:custom.profiles.${self:provider.stage}}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:GetRecords"
        - "dynamodb:Query"
        # - "dynamodb:Scan"
        # - "dynamodb:PutItem"
        # - "dynamodb:UpdateItem"
        # - "dynamodb:DeleteItem"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:dynamodb:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":table/${self:custom.dynamoTable.tblName}" ] ] }
    
plugins:
  - serverless-offline

functions:
  getNAICSCode:
    handler: ./code/naics.get
    memorySize: 128
    timeout: 10
    environment:
      REGION: ${self:custom.defaultRegion}
      STAGE: ${self:custom.defaultStage}
      TABLE_NAME: ${self:custom.dynamoTable.tblName}
      TABLE_PARTKEY: ${self:custom.dynamoTable.tblPartKey}
      TABLE_SORTKEY: ${self:custom.dynamoTable.tblSortKey}
    events:
      - http:
        method: get
        path: naics/get/{year}/{code}
  listNAICSCodes:
    handler: ./code/naics.list
    memorySize: 128
    timeout: 10
    environment:
      REGION: ${self:custom.defaultRegion}
      STAGE: ${self:custom.defaultStage}
      TABLE_NAME: ${self:custom.dynamoTable.tblName}
      TABLE_PARTKEY: ${self:custom.dynamoTable.tblPartKey}
      TABLE_SORTKEY: ${self:custom.dynamoTable.tblSortKey}
    events:
      - http:
        method: get
        path: naics/list/{year}/{code}

resources:
  Resources:
    naicsDDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.dynamoTable.tblName}
        AttributeDefinitions:
          -
            AttributeName: "NAICSYear"
            AttributeType: "S"
          -
            AttributeName: "CodeLenAndCode"
            AttributeType: "S"
          -
            AttributeName: "NAICSCode"
            AttributeType: "S"
          -
            AttributeName: "Title"
            AttributeType: "S"
          -
            AttributeName: "CodeLen"
            AttributeType: "N"
          -
            AttributeName: "Prefix2"
            AttributeType: "S"
          -
            AttributeName: "Prefix3"
            AttributeType: "S"
          -
            AttributeName: "Prefix4"
            AttributeType: "S"
          -
            AttributeName: "Prefix5"
            AttributeType: "S"
          -
            AttributeName: "SeqNum"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "NAICSYear"
            KeyType: "HASH"
          -
            AttributeName: "CodeLenAndCode"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
